---
# Docker role default variables
docker_apt_key_url: "https://download.docker.com/linux/{{'debian' if ansible_distribution == 'Debian' else 'ubuntu'}}/gpg"
docker_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/{{'debian' if ansible_distribution == 'Debian' else 'ubuntu'}} {{ ansible_distribution_release }} stable" 